@extends('layouts.app')
@section('title', 'Data Warga')
@section('content')
<main id="main-content" class="container app-main">
    <nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route($routePrefix.'.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item active">Warga</li></ol></nav>
    <header class="page-header d-flex flex-wrap justify-content-between align-items-center gap-3"><div class="d-flex gap-3"><span class="page-icon"><i class="bi bi-people"></i></span><div><p class="section-eyebrow mb-1">Master kependudukan</p><h1 class="h2 section-title mb-1">Data Warga</h1><p class="text-secondary mb-0">Daftar penduduk sesuai wilayah akses Anda.</p></div></div>@can('create', \App\Models\Citizen::class)<a class="btn btn-primary" href="{{ route($routePrefix.'.citizens.create') }}"><i class="bi bi-person-plus me-1"></i>Tambah Warga</a>@endcan</header>
    @if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
    @if(request('completeness'))
        <div class="d-flex flex-wrap align-items-center gap-2 mb-3" aria-label="Filter aktif"><span class="text-secondary small">Filter aktif:</span><span class="badge text-bg-primary">{{ request('completeness') === 'without_nik' ? 'Warga tanpa NIK' : 'Warga tanpa KK' }}</span><a class="btn btn-sm btn-outline-secondary" href="{{ route($routePrefix.'.citizens.index', request()->except('completeness', 'page')) }}">Reset filter kelengkapan</a></div>
    @endif
    <form class="card card-body border-0 shadow-sm mb-3">
        @if(request('completeness'))<input type="hidden" name="completeness" value="{{ request('completeness') }}">@endif
        <div class="row g-2"><div class="col-md"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Cari nama, NIK, atau telepon" aria-label="Cari warga"></div><div class="col-md-auto"><select class="form-select" name="status" aria-label="Filter status"><option value="">Semua status</option><option value="active" @selected(request('status') === 'active')>Aktif</option><option value="inactive" @selected(request('status') === 'inactive')>Nonaktif</option></select></div>@if($routePrefix === 'kelurahan')<div class="col-md-auto"><select class="form-select" name="rw_id" aria-label="Filter RW"><option value="">Semua RW</option>@foreach($rts->pluck('rw')->unique('id') as $rw)<option value="{{ $rw->id }}" @selected((int) request('rw_id') === $rw->id)>RW {{ $rw->code }}</option>@endforeach</select></div>@endif @if($routePrefix !== 'rt')<div class="col-md-auto"><select class="form-select" name="rt_id" aria-label="Filter RT"><option value="">Semua RT</option>@foreach($rts as $rt)<option value="{{ $rt->id }}" @selected((int) request('rt_id') === $rt->id)>RW {{ $rt->rw->code }} / RT {{ $rt->code }}</option>@endforeach</select></div>@endif<div class="col-md-auto"><button class="btn btn-outline-primary">Filter</button></div></div>
    </form>
    <div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Nama</th><th>NIK</th><th>Nomor KK</th><th>Hubungan Keluarga</th>@if($routePrefix !== 'rt')<th>Wilayah</th>@endif<th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($citizens as $citizen)@php($url=route($routePrefix.'.citizens.show', $citizen))<tr tabindex="0" data-row-url="{{ $url }}"><td><a class="fw-semibold" href="{{ $url }}">{{ $citizen->name }}</a></td><td>{{ $citizen->nik ?: '—' }}</td><td>{{ $citizen->familyCard?->family_number ?: 'Belum ada' }}</td><td>{{ $citizen->family_relationship?->label() ?: 'Belum ditentukan' }}</td>@if($routePrefix !== 'rt')<td>RW {{ $citizen->rt->rw->code }} / RT {{ $citizen->rt->code }}</td>@endif<td><span class="badge text-bg-{{ $citizen->is_active ? 'success' : 'secondary' }}">{{ $citizen->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td><a class="btn btn-outline-secondary btn-sm" href="{{ $url }}">Detail</a></td></tr>@empty<tr><td colspan="{{ $routePrefix !== 'rt' ? 7 : 6 }}" class="text-center text-secondary py-5">{{ request('completeness') ? 'Tidak ada warga yang memenuhi filter kelengkapan ini.' : 'Belum ada data warga yang sesuai dengan pencarian atau filter.' }}</td></tr>@endforelse</tbody></table></div></div>
    <div class="mt-3">{{ $citizens->links('pagination::bootstrap-5') }}</div>
</main>
@endsection
