@extends('layouts.app')
@section('title', 'Detail Warga')
@section('content')
<main class="container py-4">
    <nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route($routePrefix.'.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route($routePrefix.'.citizens.index') }}">Warga</a></li><li class="breadcrumb-item active">{{ $citizen->name }}</li></ol></nav>
    <header class="card border-0 shadow-sm mb-4"><div class="card-body p-4 p-lg-5"><div class="d-flex flex-wrap justify-content-between align-items-start gap-3"><div><p class="text-primary text-uppercase fw-semibold small mb-1">Profil Administrasi Warga</p><h1 class="h2 mb-2">{{ $citizen->name }}</h1><span class="badge rounded-pill text-bg-{{ $citizen->is_active ? 'success' : 'secondary' }} px-3 py-2">{{ $citizen->is_active ? 'Aktif' : 'Nonaktif' }}</span></div><div class="d-flex flex-wrap gap-2">@if($citizen->familyCard)<a class="btn btn-outline-primary" href="{{ route($routePrefix.'.family-cards.show', $citizen->familyCard) }}">Kembali ke Detail KK</a>@endif @can('update', $citizen)<a class="btn btn-primary" href="{{ route($routePrefix.'.citizens.edit', $citizen) }}">Edit Warga</a>@endcan</div></div></div></header>

    <div class="row g-4 mb-4"><div class="col-lg-7"><section class="card border-0 shadow-sm h-100" aria-labelledby="identity-heading"><div class="card-header bg-white border-0 p-4 pb-2"><h2 id="identity-heading" class="h5 mb-0">Identitas</h2></div><div class="card-body p-4 pt-3"><div class="row g-4"><div class="col-sm-6"><span class="text-secondary small d-block">Nama Lengkap</span><strong>{{ $citizen->name }}</strong></div><div class="col-sm-6"><span class="text-secondary small d-block">NIK</span><strong>{{ $citizen->nik ?: 'Belum diisi' }}</strong></div><div class="col-sm-6"><span class="text-secondary small d-block">Nomor Telepon</span><span>{{ $citizen->phone ?: 'Belum diisi' }}</span></div><div class="col-sm-6"><span class="text-secondary small d-block">Jenis Kelamin</span><span>{{ $citizen->gender === 'L' ? 'Laki-laki' : ($citizen->gender === 'P' ? 'Perempuan' : 'Belum diisi') }}</span></div><div class="col-sm-8"><span class="text-secondary small d-block">Tempat, Tanggal Lahir</span><span>{{ $citizen->birth_place ?: '—' }}{{ $citizen->birth_date ? ', '.$citizen->birth_date->locale('id')->isoFormat('D MMMM Y') : '' }}</span></div><div class="col-sm-4"><span class="text-secondary small d-block">Usia</span><span>{{ $citizen->birth_date ? $citizen->birth_date->age.' tahun' : 'Belum diketahui' }}</span></div></div></div></section></div>
    <div class="col-lg-5"><section class="card border-0 shadow-sm h-100" aria-labelledby="family-heading"><div class="card-header bg-white border-0 p-4 pb-2"><h2 id="family-heading" class="h5 mb-0">Keluarga</h2></div><div class="card-body p-4 pt-3"><div class="d-grid gap-3"><div><span class="text-secondary small d-block">Nomor KK</span>@if($citizen->familyCard)<a class="fw-semibold" href="{{ route($routePrefix.'.family-cards.show', $citizen->familyCard) }}">{{ $citizen->familyCard->family_number }}</a>@else<span>Belum memiliki KK</span>@endif</div><div><span class="text-secondary small d-block">Kepala Keluarga</span><span>{{ $citizen->familyCard?->headCitizen?->name ?: 'Belum ditentukan' }}</span></div><div><span class="text-secondary small d-block">Hubungan dalam Keluarga</span><span>{{ $citizen->family_relationship?->label() ?: 'Belum ditentukan' }}</span></div></div></div></section></div></div>

    <section class="card border-0 shadow-sm mb-4" aria-labelledby="domicile-heading"><div class="card-header bg-white border-0 p-4 pb-2"><h2 id="domicile-heading" class="h5 mb-0">Domisili</h2></div><div class="card-body p-4 pt-3"><div class="row g-4"><div class="col-md-4"><span class="text-secondary small d-block">Wilayah</span><strong>RW {{ $citizen->rt->rw->code }} / RT {{ $citizen->rt->code }}</strong></div><div class="col-md-8"><span class="text-secondary small d-block">Alamat</span><span>{{ $citizen->address ?: $citizen->familyCard?->address ?: 'Belum diisi' }}</span></div></div></div></section>

    <section class="card border-0 shadow-sm" aria-labelledby="service-heading"><div class="card-header bg-white border-0 p-4"><h2 id="service-heading" class="h5 mb-1">Riwayat Layanan</h2><p class="text-secondary small mb-0">Riwayat laporan yang tercatat atas nama warga.</p></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Tiket</th><th>Judul</th><th>Status</th><th>Tanggal</th><th>Aksi</th></tr></thead><tbody>@forelse($citizen->reports as $report)<tr><td class="fw-semibold">{{ $report->ticket_number }}</td><td>{{ $report->title }}</td><td><span class="badge text-bg-{{ $report->status->bootstrapColor() }}">{{ $report->status->label() }}</span></td><td>{{ $report->reported_at->locale('id')->isoFormat('D MMM Y') }}</td><td><a class="btn btn-outline-secondary btn-sm" href="{{ route('reports.show', $report) }}">Detail</a></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-5">Belum ada riwayat laporan untuk warga ini.</td></tr>@endforelse</tbody></table></div></section>
</main>
@endsection
