@extends('layouts.app')
@section('title', 'Administrasi Surat')
@section('content')
<main id="main-content" class="container app-main">
    <nav aria-label="Breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route($routePrefix.'.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item active" aria-current="page">Surat</li></ol></nav>
    <header class="page-header d-flex flex-wrap justify-content-between align-items-end gap-3">
        <div class="d-flex align-items-start gap-3"><span class="page-icon" aria-hidden="true"><i class="bi bi-envelope-paper"></i></span><div><p class="section-eyebrow mb-1">Pelayanan administrasi</p><h1 class="h2 section-title mb-1">{{ $routePrefix === 'rt' ? 'Pengajuan Surat' : ($routePrefix === 'rw' ? 'Verifikasi Surat' : 'Administrasi Surat') }}</h1><p class="text-secondary mb-0">Kelola alur surat warga sesuai kewenangan Anda.</p></div></div>
        @can('create', \App\Models\VillageLetter::class)<a class="btn btn-primary" href="{{ route('rt.letters.create') }}"><i class="bi bi-plus-lg me-1" aria-hidden="true"></i>Buat Pengajuan</a>@endcan
    </header>

    <div class="d-flex flex-wrap gap-2 mb-3" aria-label="Filter cepat surat">
        <a class="btn btn-sm {{ request('date_from') === now()->toDateString() ? 'btn-primary' : 'btn-outline-primary' }}" href="{{ route($routePrefix.'.letters.index', ['date_from' => now()->toDateString(), 'date_to' => now()->toDateString()]) }}"><i class="bi bi-calendar-day me-1"></i>Hari Ini</a>
        <a class="btn btn-sm {{ request('status') === 'RW_REVIEWED' ? 'btn-warning' : 'btn-outline-warning' }}" href="{{ route($routePrefix.'.letters.index', ['status' => 'RW_REVIEWED']) }}"><i class="bi bi-hourglass-split me-1"></i>Diproses</a>
        <a class="btn btn-sm {{ request('status') === 'ISSUED' ? 'btn-success' : 'btn-outline-success' }}" href="{{ route($routePrefix.'.letters.index', ['status' => 'ISSUED']) }}"><i class="bi bi-check-circle me-1"></i>Terbit</a>
        <a class="btn btn-sm {{ request('status') === 'REJECTED' ? 'btn-danger' : 'btn-outline-danger' }}" href="{{ route($routePrefix.'.letters.index', ['status' => 'REJECTED']) }}"><i class="bi bi-x-circle me-1"></i>Ditolak</a>
    </div>

    <form class="filter-panel p-3 p-lg-4 mb-4" method="GET" aria-labelledby="filter-title">
        <h2 id="filter-title" class="h6 section-title mb-3"><i class="bi bi-funnel me-2" aria-hidden="true"></i>Filter Surat</h2>
        <div class="row g-3 align-items-end">
            <div class="col-12 col-lg"><label class="form-label" for="letter-search">Pencarian</label><div class="input-group"><span class="input-group-text"><i class="bi bi-search"></i></span><input id="letter-search" name="search" value="{{ request('search') }}" class="form-control" placeholder="Nama, NIK, atau nomor surat"></div></div>
            <div class="col-sm-6 col-lg-auto"><label class="form-label" for="letter-type">Jenis</label><select id="letter-type" name="type" class="form-select"><option value="">Semua jenis</option>@foreach(\App\Enums\LetterType::cases() as $type)<option value="{{ $type->value }}" @selected(request('type') === $type->value)>{{ $type->label() }}</option>@endforeach</select></div>
            <div class="col-sm-6 col-lg-auto"><label class="form-label" for="letter-status">Status</label><select id="letter-status" name="status" class="form-select"><option value="">Semua status</option>@foreach(\App\Enums\LetterStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>
            @if($routePrefix === 'kelurahan')<div class="col-sm-6 col-lg-auto"><label class="form-label" for="rw-filter">RW</label><select id="rw-filter" name="rw_id" class="form-select"><option value="">Semua RW</option>@foreach($rts->pluck('rw')->unique('id') as $rw)<option value="{{ $rw->id }}" @selected((int) request('rw_id') === $rw->id)>RW {{ $rw->code }}</option>@endforeach</select></div>@endif
            @if($routePrefix !== 'rt')<div class="col-sm-6 col-lg-auto"><label class="form-label" for="rt-filter">RT</label><select id="rt-filter" name="rt_id" class="form-select"><option value="">Semua RT</option>@foreach($rts as $rt)<option value="{{ $rt->id }}" @selected((int) request('rt_id') === $rt->id)>RW {{ $rt->rw->code }}/RT {{ $rt->code }}</option>@endforeach</select></div>@endif
            @if($routePrefix === 'kelurahan')<div class="col-sm-6 col-lg-auto"><label class="form-label" for="date-from">Dari</label><input id="date-from" type="date" name="date_from" value="{{ request('date_from') }}" class="form-control"></div><div class="col-sm-6 col-lg-auto"><label class="form-label" for="date-to">Sampai</label><input id="date-to" type="date" name="date_to" value="{{ request('date_to') }}" class="form-control"></div>@endif
            <div class="col-12 col-lg-auto d-flex gap-2"><button class="btn btn-primary" type="submit"><i class="bi bi-search me-1"></i>Terapkan</button><a class="btn btn-outline-secondary" href="{{ route($routePrefix.'.letters.index') }}" aria-label="Reset filter"><i class="bi bi-arrow-counterclockwise"></i></a></div>
        </div>
    </form>

    <section class="card border-0" aria-labelledby="letter-list-title"><div class="card-header bg-white p-4 d-flex justify-content-between align-items-center"><h2 id="letter-list-title" class="h5 section-title mb-0">Daftar Surat</h2><span class="badge text-bg-primary badge-status">{{ number_format($letters->total()) }} data</span></div><div class="table-responsive"><table class="table table-hover table-sticky align-middle mb-0"><thead><tr><th>Nomor</th><th>Warga</th><th>Jenis</th><th>Wilayah</th><th>Status</th><th>Tanggal</th><th><span class="visually-hidden">Aksi</span></th></tr></thead><tbody>
        @forelse($letters as $letter)@php($url = route($routePrefix.'.letters.show', $letter))<tr data-row-url="{{ $url }}" aria-label="Buka detail surat {{ $letter->citizen->name }}"><td class="fw-semibold">{{ $letter->letter_number ?: 'Belum terbit' }}</td><td><a class="fw-semibold" href="{{ $url }}">{{ $letter->citizen->name }}</a><small class="d-block text-secondary">{{ $letter->citizen->nik ?: 'NIK belum diisi' }}</small></td><td>{{ $letter->letter_type->label() }}</td><td>RW {{ $letter->rt->rw->code }}/RT {{ $letter->rt->code }}</td><td><span class="badge badge-status text-bg-{{ $letter->status->bootstrapColor() }}">{{ $letter->status->label() }}</span></td><td>{{ $letter->created_at->locale('id')->isoFormat('D MMM Y') }}</td><td><a class="btn btn-outline-primary btn-sm" href="{{ $url }}" aria-label="Detail surat {{ $letter->citizen->name }}"><i class="bi bi-chevron-right"></i></a></td></tr>
        @empty<tr><td colspan="7"><div class="empty-state"><span class="empty-state-icon"><i class="bi bi-inbox"></i></span><h3 class="h5">Belum ada pengajuan surat</h3><p class="text-secondary">Belum ada data yang cocok dengan pencarian atau filter yang dipilih.</p>@can('create', \App\Models\VillageLetter::class)<a class="btn btn-primary" href="{{ route('rt.letters.create') }}"><i class="bi bi-plus-lg me-1"></i>Buat Pengajuan</a>@else<a class="btn btn-outline-primary" href="{{ route($routePrefix.'.letters.index') }}">Reset Filter</a>@endcan</div></td></tr>@endforelse
    </tbody></table></div>@if($letters->hasPages())<div class="card-footer bg-white p-3 d-flex justify-content-center">{{ $letters->links('pagination::bootstrap-5') }}</div>@endif</section>
</main>
@endsection
