@extends('layouts.app')
@section('title', 'Detail Surat')
@section('content')
<main id="main-content" class="container app-main">
    <nav aria-label="Breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route($routePrefix.'.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route($routePrefix.'.letters.index') }}">Surat</a></li><li class="breadcrumb-item active" aria-current="page">Detail</li></ol></nav>
    @if(session('status'))<div class="alert alert-success" role="status"><i class="bi bi-check-circle me-2"></i>{{ session('status') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger" role="alert"><i class="bi bi-exclamation-triangle me-2"></i>{{ $errors->first() }}</div>@endif

    <header class="card border-0 mb-4"><div class="card-body p-4 p-lg-5 d-flex flex-wrap justify-content-between align-items-start gap-3"><div class="d-flex gap-3"><span class="page-icon"><i class="bi bi-file-earmark-text"></i></span><div><p class="section-eyebrow mb-1">{{ $letter->letter_number ?: 'Nomor belum diterbitkan' }}</p><h1 class="h2 section-title mb-1">{{ $letter->typeLabel() }}</h1>@if($letter->isGenericSubmission())<span class="badge text-bg-primary mb-2">Pengajuan Dinamis</span>@endif<p class="text-secondary mb-1">Nomor pengajuan: <strong>{{ $letter->public_tracking_code }}</strong></p><p class="text-secondary mb-0">Diajukan {{ $letter->created_at->locale('id')->isoFormat('D MMMM Y') }}</p></div></div><span class="badge badge-status text-bg-{{ $letter->status->bootstrapColor() }} fs-6"><i class="bi bi-circle-fill me-1 small"></i>{{ $letter->status->label() }}</span></div></header>

    <section class="card border-0 mb-4" aria-labelledby="timeline-title"><div class="card-body p-4"><h2 id="timeline-title" class="h5 section-title mb-4"><i class="bi bi-clock-history me-2 text-primary"></i>Timeline Status</h2><ol class="timeline">@foreach($letter->histories as $history)<li class="timeline-item"><span class="timeline-icon"><i class="bi bi-check2"></i></span><strong>{{ $history->new_status->label() }}</strong><span class="d-block text-secondary small">{{ $history->created_at->locale('id')->isoFormat('D MMM Y, HH:mm') }} · {{ $history->user?->name ?: 'Sistem' }}</span>@if($history->note)<p class="mb-0 mt-2">{{ $history->note }}</p>@endif</li>@endforeach</ol></div></section>

    <div class="row g-4">
        <div class="col-lg-8">
            <section class="card border-0 mb-4" aria-labelledby="applicant-title"><div class="card-header bg-white border-0 p-4 pb-2"><h2 id="applicant-title" class="h5 section-title mb-0"><i class="bi bi-person-vcard me-2 text-primary"></i>Informasi Pemohon</h2></div><div class="card-body p-4 pt-3"><dl class="row mb-0 gy-3"><dt class="col-sm-4 text-secondary">Nama</dt><dd class="col-sm-8 fw-semibold">{{ $letter->citizen->name }}</dd><dt class="col-sm-4 text-secondary">NIK</dt><dd class="col-sm-8">{{ $letter->citizen->nik ?: 'Belum diisi' }}</dd><dt class="col-sm-4 text-secondary">Alamat</dt><dd class="col-sm-8">{{ $letter->citizen->address ?: $letter->citizen->familyCard?->address ?: 'Belum diisi' }}</dd></dl></div></section>
            <section class="card border-0 mb-4" aria-labelledby="kk-title"><div class="card-header bg-white border-0 p-4 pb-2"><h2 id="kk-title" class="h5 section-title mb-0"><i class="bi bi-people me-2 text-primary"></i>Informasi KK</h2></div><div class="card-body p-4 pt-3"><dl class="row mb-0 gy-3"><dt class="col-sm-4 text-secondary">Nomor KK</dt><dd class="col-sm-8 fw-semibold">{{ $letter->citizen->familyCard?->family_number ?: 'Belum memiliki KK' }}</dd><dt class="col-sm-4 text-secondary">Wilayah</dt><dd class="col-sm-8">RW {{ $letter->rt->rw->code }} / RT {{ $letter->rt->code }}</dd></dl></div></section>
            <section class="card border-0 mb-4" aria-labelledby="letter-info-title"><div class="card-header bg-white border-0 p-4 pb-2"><h2 id="letter-info-title" class="h5 section-title mb-0"><i class="bi bi-file-text me-2 text-primary"></i>Informasi Surat</h2></div><div class="card-body p-4 pt-3"><dl class="row mb-0 gy-3"><dt class="col-sm-4 text-secondary">Jenis Surat</dt><dd class="col-sm-8">{{ $letter->typeLabel() }}</dd><dt class="col-sm-4 text-secondary">Level Persetujuan</dt><dd class="col-sm-8">{{ $letter->required_approval_level?->label() ?: 'Mengikuti workflow configuration (Phase 4)' }}</dd><dt class="col-sm-4 text-secondary">Tujuan</dt><dd class="col-sm-8">{{ $letter->purpose }}</dd><dt class="col-sm-4 text-secondary">Catatan</dt><dd class="col-sm-8">{{ $letter->notes ?: 'Tidak ada' }}</dd></dl></div></section>
            @if($letter->submission)
                <section class="card border-0 mb-4" aria-labelledby="submitted-fields-title"><div class="card-header bg-white border-0 p-4 pb-2"><h2 id="submitted-fields-title" class="h5 section-title mb-0"><i class="bi bi-ui-checks me-2 text-primary"></i>Data Formulir Version {{ $letter->submission->version_number }}</h2></div><div class="card-body p-4 pt-3"><dl class="row mb-0 gy-3">@forelse($letter->submission->fieldValues as $fieldValue)<dt class="col-sm-4 text-secondary">{{ $fieldValue->field_label }}</dt><dd class="col-sm-8">@if($fieldValue->submitted_value === null)<span class="text-secondary">Tidak diisi</span>@elseif($fieldValue->field_type === \App\Enums\LetterFieldType::BOOLEAN){{ $fieldValue->submitted_value ? 'Ya' : 'Tidak' }}@else{{ $fieldValue->submitted_value }}@endif</dd>@empty<dd class="col-12 text-secondary">Tidak ada field tambahan.</dd>@endforelse</dl></div></section>
                <section class="card border-0 mb-4" aria-labelledby="submitted-requirements-title"><div class="card-header bg-white border-0 p-4 pb-2"><h2 id="submitted-requirements-title" class="h5 section-title mb-0"><i class="bi bi-paperclip me-2 text-primary"></i>Persyaratan</h2></div><div class="card-body p-4 pt-3"><ul class="list-group list-group-flush">@forelse($letter->submission->requirements as $requirement)<li class="list-group-item px-0 d-flex justify-content-between gap-3"><div><strong>{{ $requirement->requirement_label }}</strong><small class="d-block text-secondary">{{ $requirement->evidence_type->label() }}</small></div><span class="badge text-bg-{{ $requirement->status->bootstrapColor() }} align-self-start">{{ $requirement->status->label() }}</span></li>@empty<li class="list-group-item px-0 text-secondary">Tidak ada persyaratan.</li>@endforelse</ul></div></section>
            @endif
            <section class="card border-0" aria-labelledby="history-title"><div class="card-body p-4"><h2 id="history-title" class="h5 section-title mb-2"><i class="bi bi-journal-text me-2 text-primary"></i>Riwayat</h2><p class="text-secondary mb-0">{{ $letter->histories->count() }} aktivitas tercatat pada pengajuan ini. Rincian kronologis tersedia pada timeline di atas.</p></div></section>
        </div>
        <aside class="col-lg-4"><section class="card action-panel border-0 position-sticky" style="top: 1rem" aria-labelledby="actions-title"><div class="card-body p-4"><h2 id="actions-title" class="h5 section-title mb-2">Panel Aksi</h2><p class="text-secondary small">Tindakan tersedia sesuai status dan level persetujuan template.</p><div class="d-grid gap-2">
            @can('update', $letter)<a class="btn btn-outline-primary" href="{{ route('rt.letters.edit', $letter) }}"><i class="bi bi-pencil me-1"></i>Edit Draft</a>@endcan
            @can('submit', $letter)<form method="POST" action="{{ route('rt.letters.submit', $letter) }}">@csrf @method('PATCH')<button class="btn btn-primary w-100"><i class="bi bi-send me-1"></i>{{ $letter->required_approval_level === \App\Enums\LetterApprovalLevel::RT ? 'Setujui di RT' : 'Ajukan ke RW' }}</button></form>@endcan
            @can('review', $letter)<form method="POST" action="{{ route('rw.letters.review', $letter) }}">@csrf @method('PATCH')<button class="btn btn-primary w-100"><i class="bi bi-patch-check me-1"></i>{{ $letter->required_approval_level === \App\Enums\LetterApprovalLevel::RW ? 'Setujui di RW' : 'Verifikasi dan Teruskan' }}</button></form>@endcan
            @can('approve', $letter)<form method="POST" action="{{ route('kelurahan.letters.approve', $letter) }}">@csrf @method('PATCH')<button class="btn btn-primary w-100"><i class="bi bi-check2-circle me-1"></i>Setujui Surat</button></form>@endcan
            @can('issue', $letter)<form method="POST" action="{{ route($routePrefix.'.letters.issue', $letter) }}">@csrf @method('PATCH')<button class="btn btn-success w-100"><i class="bi bi-file-earmark-check me-1"></i>Terbitkan Nomor Surat</button></form>@endcan
            @can('reject', $letter)<form class="border-top mt-2 pt-3" method="POST" action="{{ route($routePrefix.'.letters.reject', $letter) }}">@csrf @method('PATCH')<label class="form-label required" for="rejection-note">Alasan Penolakan</label><textarea id="rejection-note" name="note" class="form-control mb-2" rows="3" required aria-describedby="rejection-help"></textarea><div id="rejection-help" class="form-text mb-2">Jelaskan alasan agar petugas dapat menindaklanjuti.</div><button class="btn btn-outline-danger w-100"><i class="bi bi-x-circle me-1"></i>Tolak</button></form>@endcan
            @can('downloadPdf', $letter)<a class="btn btn-outline-success" href="{{ route($routePrefix.'.letters.pdf', $letter) }}"><i class="bi bi-file-earmark-pdf me-1"></i>Unduh PDF</a>@endcan
        </div></div></section></aside>
    </div>
</main>
@endsection
