@extends('layouts.app')
@section('title', 'Kartu Keluarga')
@section('content')
<main id="main-content" class="container app-main">
    <nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route($routePrefix.'.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item active">Kartu Keluarga</li></ol></nav>
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-3"><div><h1 class="h3 mb-1">Kartu Keluarga</h1><p class="text-secondary mb-0">Administrasi keluarga sesuai wilayah akses Anda.</p></div>@can('create', \App\Models\FamilyCard::class)<a class="btn btn-primary" href="{{ route($routePrefix.'.family-cards.create') }}">Tambah Kartu Keluarga</a>@endcan</div>
    @if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
    <form class="card card-body border-0 shadow-sm mb-3"><div class="row g-2"><div class="col-md"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Cari nomor KK atau kepala keluarga" aria-label="Cari Kartu Keluarga"></div><div class="col-md-auto"><select class="form-select" name="status" aria-label="Filter status"><option value="">Semua status</option><option value="active" @selected(request('status') === 'active')>Aktif</option><option value="inactive" @selected(request('status') === 'inactive')>Nonaktif</option></select></div>@if($routePrefix === 'kelurahan')<div class="col-md-auto"><select class="form-select" name="rw_id" aria-label="Filter RW"><option value="">Semua RW</option>@foreach($rts->pluck('rw')->unique('id') as $rw)<option value="{{ $rw->id }}" @selected((int) request('rw_id') === $rw->id)>RW {{ $rw->code }}</option>@endforeach</select></div>@endif @if($routePrefix !== 'rt')<div class="col-md-auto"><select class="form-select" name="rt_id" aria-label="Filter RT"><option value="">Semua RT</option>@foreach($rts as $rt)<option value="{{ $rt->id }}" @selected((int) request('rt_id') === $rt->id)>RW {{ $rt->rw->code }} / RT {{ $rt->code }}</option>@endforeach</select></div>@endif<div class="col-md-auto"><button class="btn btn-outline-primary">Filter</button></div></div></form>
    <div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Nomor KK</th><th>Kepala Keluarga</th><th>Alamat</th><th>Anggota</th><th>Kelengkapan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($familyCards as $card)@php($url=route($routePrefix.'.family-cards.show', $card))<tr tabindex="0" data-row-url="{{ $url }}"><td><a class="fw-semibold" href="{{ $url }}">{{ $card->family_number }}</a><div class="small text-secondary">RW {{ $card->rt->rw->code }} / RT {{ $card->rt->code }}</div></td><td>{{ $card->headCitizen?->name ?: 'Belum ditentukan' }}</td><td><span title="{{ $card->address }}">{{ \Illuminate\Support\Str::limit($card->address ?: 'Belum diisi', 45) }}</span></td><td>{{ $card->citizens_count }} orang</td><td>@if(!$card->head_citizen_id)<span class="badge text-bg-warning">Belum ada kepala keluarga</span>@elseif($card->citizens_without_nik_count > 0)<span class="badge text-bg-warning">Ada anggota tanpa NIK</span>@else<span class="badge text-bg-success">Lengkap</span>@endif</td><td><span class="badge text-bg-{{ $card->is_active ? 'success' : 'secondary' }}">{{ $card->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td><a class="btn btn-outline-secondary btn-sm" href="{{ $url }}">Detail</a></td></tr>@empty<tr><td colspan="7" class="text-center text-secondary py-5">Belum ada Kartu Keluarga yang sesuai dengan pencarian atau filter.</td></tr>@endforelse</tbody></table></div></div>
    <div class="mt-3">{{ $familyCards->links('pagination::bootstrap-5') }}</div>
</main>
@endsection
