@extends('layouts.app')
@section('title', 'Detail Kartu Keluarga')
@section('content')
@php
    $activeMembers = $familyCard->citizens->where('is_active', true)->count();
    $membersWithoutNik = $familyCard->citizens->whereNull('nik')->count();
    $membersWithoutPhone = $familyCard->citizens->whereNull('phone')->count();
    $inactiveMembers = $familyCard->citizens->where('is_active', false)->count();
@endphp
<main id="main-content" class="container app-main">
    <nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route($routePrefix.'.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route($routePrefix.'.family-cards.index') }}">Kartu Keluarga</a></li><li class="breadcrumb-item active">{{ $familyCard->family_number }}</li></ol></nav>
    @if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
    @if($familyCard->headCitizen && !$familyCard->headCitizen->is_active)<div class="alert alert-warning">Kepala keluarga saat ini berstatus nonaktif. Pilih anggota aktif sebagai pengganti bila diperlukan.</div>@endif

    <header class="card border-0 shadow-sm mb-4"><div class="card-body p-4 p-lg-5"><div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><p class="text-primary text-uppercase fw-semibold small mb-1">Administrasi Keluarga</p><h1 class="h2 mb-0">KK {{ $familyCard->family_number }}</h1></div><span class="badge rounded-pill text-bg-{{ $familyCard->is_active ? 'success' : 'secondary' }} px-3 py-2">{{ $familyCard->is_active ? 'Aktif' : 'Nonaktif' }}</span></div><div class="row g-4"><div class="col-md-6 col-lg-3"><span class="text-secondary small d-block">Kepala Keluarga</span><strong>{{ $familyCard->headCitizen?->name ?: 'Belum ditentukan' }}</strong></div><div class="col-md-6 col-lg-3"><span class="text-secondary small d-block">Wilayah</span><strong>RW {{ $familyCard->rt->rw->code }} / RT {{ $familyCard->rt->code }}</strong></div><div class="col-md-6 col-lg-2"><span class="text-secondary small d-block">Jumlah Anggota</span><strong>{{ $familyCard->citizens_count }} orang</strong></div><div class="col-md-6 col-lg-4"><span class="text-secondary small d-block">Alamat</span><span>{{ $familyCard->address ?: 'Belum diisi' }}</span></div></div></div></header>

    <section class="card border-0 shadow-sm mb-4" aria-labelledby="family-info-heading"><div class="card-header bg-white border-0 p-4 pb-2"><h2 id="family-info-heading" class="h5 mb-0">Informasi Kartu Keluarga</h2></div><div class="card-body p-4 pt-3"><div class="row g-3"><div class="col-sm-6 col-lg"><div class="border rounded-3 p-3 h-100"><span class="small text-secondary d-block">Nomor KK</span><strong>{{ $familyCard->family_number }}</strong></div></div><div class="col-sm-6 col-lg"><div class="border rounded-3 p-3 h-100"><span class="small text-secondary d-block">Kepala Keluarga</span><strong>{{ $familyCard->headCitizen?->name ?: 'Belum ditentukan' }}</strong></div></div><div class="col-sm-6 col-lg"><div class="border rounded-3 p-3 h-100"><span class="small text-secondary d-block">Status</span><strong>{{ $familyCard->is_active ? 'Aktif' : 'Nonaktif' }}</strong></div></div></div></div></section>

    <section class="card border-0 shadow-sm mb-4" aria-labelledby="members-heading">
        <div class="card-header bg-white border-0 p-4 d-flex flex-wrap justify-content-between align-items-center gap-3">
            <div><h2 id="members-heading" class="h5 mb-1">Daftar Anggota Keluarga</h2><p class="text-secondary small mb-0">{{ $familyCard->citizens_count }} anggota terdaftar dalam KK ini.</p></div>
            @can('update', $familyCard)<a class="btn btn-primary" href="{{ route($routePrefix.'.family-cards.members.create', $familyCard) }}">Tambah Anggota</a>@endcan
        </div>
        <div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Nama</th><th>NIK</th><th>Hubungan</th><th>Jenis Kelamin</th><th>Tempat/Tanggal Lahir</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
            @forelse($familyCard->citizens as $citizen)
                @php($url=route($routePrefix.'.citizens.show', $citizen))
                <tr class="{{ $familyCard->head_citizen_id === $citizen->id ? 'table-primary' : '' }}" tabindex="0" data-row-url="{{ $url }}"><td><a href="{{ $url }}" class="fw-semibold">{{ $citizen->name }}</a>@if($familyCard->head_citizen_id === $citizen->id)<span class="badge text-bg-primary ms-1">Kepala Keluarga</span>@endif</td><td>{{ $citizen->nik ?: '—' }}</td><td>{{ $citizen->family_relationship?->label() ?: 'Belum ditentukan' }}</td><td>{{ $citizen->gender === 'L' ? 'Laki-laki' : ($citizen->gender === 'P' ? 'Perempuan' : '—') }}</td><td>{{ $citizen->birth_place ?: '—' }}{{ $citizen->birth_date ? ', '.$citizen->birth_date->locale('id')->isoFormat('D MMM Y') : '' }}</td><td><span class="badge text-bg-{{ $citizen->is_active ? 'success' : 'secondary' }}">{{ $citizen->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-secondary btn-sm" href="{{ $url }}">Detail</a>@can('update', $familyCard) @if($familyCard->head_citizen_id !== $citizen->id)<form method="POST" action="{{ route($routePrefix.'.family-cards.head.update', [$familyCard, $citizen]) }}">@csrf @method('PATCH')<button class="btn btn-outline-primary btn-sm">Jadikan Kepala Keluarga</button></form>@endif @endcan</div></td></tr>
            @empty
                <tr><td colspan="7"><div class="text-center text-secondary py-5"><h3 class="h6 text-body">KK belum memiliki anggota</h3><p class="mb-3">Gunakan tombol “Tambah Anggota” untuk mencatat anggota keluarga pertama.</p>@can('update', $familyCard)<a class="btn btn-primary btn-sm" href="{{ route($routePrefix.'.family-cards.members.create', $familyCard) }}">Tambah Anggota</a>@endcan</div></td></tr>
            @endforelse
        </tbody></table></div>
    </section>

    <section class="card border-0 shadow-sm mb-4" aria-labelledby="completeness-heading"><div class="card-header bg-white border-0 p-4 pb-2"><h2 id="completeness-heading" class="h5 mb-0">Informasi Kelengkapan Data</h2></div><div class="card-body p-4"><div class="row g-3"><div class="col-sm-6 col-lg"><div class="border rounded-3 p-3 h-100"><span class="badge rounded-pill text-bg-{{ $familyCard->head_citizen_id ? 'success' : 'warning' }} d-inline-flex mb-1">{{ $familyCard->head_citizen_id ? 'Sudah ditentukan' : 'Belum ditentukan' }}</span><span class="small text-secondary d-block">Status Kepala Keluarga</span></div></div><div class="col-sm-6 col-lg"><div class="border rounded-3 p-3 h-100"><strong class="fs-4 d-block">{{ $membersWithoutNik }}</strong><span class="small text-secondary">Anggota tanpa NIK</span></div></div><div class="col-sm-6 col-lg"><div class="border rounded-3 p-3 h-100"><strong class="fs-4 d-block">{{ $membersWithoutPhone }}</strong><span class="small text-secondary">Anggota tanpa nomor telepon</span></div></div><div class="col-sm-6 col-lg"><div class="border rounded-3 p-3 h-100"><strong class="fs-4 d-block">{{ $inactiveMembers }}</strong><span class="small text-secondary">Anggota nonaktif</span></div></div><div class="col-sm-6 col-lg"><div class="border rounded-3 p-3 h-100"><strong class="fs-4 d-block">{{ $activeMembers }}</strong><span class="small text-secondary">Total anggota aktif</span></div></div></div></div></section>

    <section class="card border-0 shadow-sm" aria-labelledby="actions-heading"><div class="card-body p-4"><h2 id="actions-heading" class="h5 mb-3">Aksi Administratif</h2>@can('update', $familyCard)<div class="d-flex flex-wrap gap-2"><a class="btn btn-primary" href="{{ route($routePrefix.'.family-cards.members.create', $familyCard) }}">Tambah Anggota</a><a class="btn btn-outline-primary" href="{{ route($routePrefix.'.family-cards.edit', $familyCard) }}">Edit KK</a><form method="POST" action="{{ route($routePrefix.'.family-cards.status.toggle', $familyCard) }}">@csrf @method('PATCH')<button class="btn btn-outline-{{ $familyCard->is_active ? 'danger' : 'success' }}">{{ $familyCard->is_active ? 'Nonaktifkan' : 'Aktifkan' }} KK</button></form></div>@else<p class="text-secondary mb-0">Data ditampilkan dalam mode baca saja.</p>@endcan</div></section>
</main>
@endsection