@php($editing = isset($managedUser))
<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="name">Nama</label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $managedUser->name ?? '') }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="email">Email</label><input class="form-control @error('email') is-invalid @enderror" id="email" name="email" type="email" value="{{ old('email', $managedUser->email ?? '') }}" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    @unless ($editing)
        <div class="col-md-6"><label class="form-label" for="password">Password</label><input class="form-control @error('password') is-invalid @enderror" id="password" name="password" type="password" autocomplete="new-password" required>@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror<div class="form-text">Minimal 12 karakter.</div></div>
        <div class="col-md-6"><label class="form-label" for="password_confirmation">Konfirmasi password</label><input class="form-control" id="password_confirmation" name="password_confirmation" type="password" autocomplete="new-password" required></div>
    @endunless
    <div class="col-md-4"><label class="form-label" for="role">Jenis Akun</label><select class="form-select @error('role') is-invalid @enderror" id="role" name="role" required><option value="KELURAHAN" @selected(old('role', $managedUser->role->value ?? '') === 'KELURAHAN')>Akun Internal Desa</option><option value="RW" @selected(old('role', $managedUser->role->value ?? '') === 'RW')>Petugas RW</option><option value="RT" @selected(old('role', $managedUser->role->value ?? '') === 'RT')>Petugas RT</option></select>@error('role')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="position">Jabatan Desa</label><select class="form-select @error('position') is-invalid @enderror" id="position" name="position"><option value="">Tanpa jabatan desa</option>@foreach (\App\Enums\VillagePosition::cases() as $position)<option value="{{ $position->value }}" @selected(old('position', $managedUser->position->value ?? '') === $position->value)>{{ $position->label() }}</option>@endforeach</select>@error('position')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="rw_id">RW</label><select class="form-select @error('rw_id') is-invalid @enderror" id="rw_id" name="rw_id"><option value="">Tanpa RW</option>@foreach ($rws as $rw)<option value="{{ $rw->id }}" @selected((int) old('rw_id', $managedUser->rw_id ?? 0) === $rw->id)>{{ $rw->code }} — {{ $rw->name }}</option>@endforeach</select>@error('rw_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="rt_id">RT</label><select class="form-select @error('rt_id') is-invalid @enderror" id="rt_id" name="rt_id"><option value="">Tanpa RT</option>@foreach ($rts as $rt)<option value="{{ $rt->id }}" @selected((int) old('rt_id', $managedUser->rt_id ?? 0) === $rt->id)>{{ $rt->rw?->code }} · {{ $rt->code }} — {{ $rt->name }}</option>@endforeach</select>@error('rt_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div>
<div class="alert alert-light border small mt-4 mb-0"><strong>Aturan penempatan:</strong> akun internal desa memilih jabatan tanpa wilayah; Petugas RW wajib memilih RW; Petugas RT wajib memilih RW dan RT yang sesuai.</div>
