@extends('layouts.app')
@section('title', 'Edit Pengguna - SIGAP WARGA')
@section('content')
    <div class="admin-dashboard min-vh-100"><main class="container py-4 py-lg-5" style="max-width: 960px;">
        <nav aria-label="breadcrumb"><ol class="breadcrumb small"><li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}">Pengguna</a></li><li class="breadcrumb-item active" aria-current="page">{{ $managedUser->name }}</li></ol></nav>
        <div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="admin-eyebrow mb-1">Administrasi Akses</p><h1 class="h2 fw-bold mb-1">Edit Pengguna</h1><p class="text-secondary mb-0">Perbarui identitas, role, dan penempatan akun.</p></div><span class="badge rounded-pill text-bg-{{ $managedUser->is_active ? 'success' : 'secondary' }} px-3 py-2">{{ $managedUser->is_active ? 'Aktif' : 'Nonaktif' }}</span></div>
        @if (session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
        <section class="card admin-panel border-0 shadow-sm mb-4"><form method="POST" action="{{ route('admin.users.update', $managedUser) }}">@csrf @method('PUT')<div class="card-body p-4"><h2 class="h5 fw-bold mb-3">Data Pengguna</h2>@include('admin.users._form')</div><div class="card-footer bg-white border-top p-4 d-flex gap-2"><button class="btn btn-primary" type="submit">Simpan Perubahan</button><a class="btn btn-outline-secondary" href="{{ route('admin.users.index') }}">Kembali</a></div></form></section>
        <div class="row g-4">
            <div class="col-lg-6"><section class="card admin-panel border-0 shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 fw-bold">Status Akun</h2><p class="text-secondary small">Akun nonaktif tidak dapat login. Session aktif juga akan dicabut.</p>@if (auth()->user()->is($managedUser))<div class="alert alert-warning small mb-0">Anda tidak dapat menonaktifkan akun sendiri.</div>@else<form method="POST" action="{{ route('admin.users.status.toggle', $managedUser) }}">@csrf @method('PATCH')<button class="btn btn-{{ $managedUser->is_active ? 'outline-danger' : 'success' }}" type="submit">{{ $managedUser->is_active ? 'Nonaktifkan Akun' : 'Aktifkan Akun' }}</button></form>@endif</div></section></div>
            <div class="col-lg-6"><section class="card admin-panel border-0 shadow-sm h-100"><div class="card-body p-4"><h2 class="h5 fw-bold">Reset Password</h2><p class="text-secondary small">Password lama dan seluruh session pengguna akan dicabut.</p><form method="POST" action="{{ route('admin.users.password.reset', $managedUser) }}">@csrf @method('PATCH')<div class="mb-3"><label class="form-label" for="password">Password baru</label><input class="form-control @error('password') is-invalid @enderror" id="password" name="password" type="password" autocomplete="new-password" required>@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="mb-3"><label class="form-label" for="password_confirmation">Konfirmasi password</label><input class="form-control" id="password_confirmation" name="password_confirmation" type="password" autocomplete="new-password" required></div><button class="btn btn-outline-primary" type="submit">Reset Password</button></form></div></section></div>
        </div>
    </main></div>
@endsection
