@extends('layouts.app')

@section('title', 'Configuration Jenis Surat - SIGAP WARGA')

@section('content')
    @php
        $isEditable = $version->isDraft() && auth()->user()->can('updateConfiguration', $version);
        $unconfiguredRequirements = $version->requirements->filter(fn ($requirement) => $requirement->evidence_type === null || $requirement->evidence_type === \App\Enums\LetterRequirementEvidenceType::UNCONFIGURED)->count();
    @endphp
    <main class="container py-4 py-lg-5">
        <nav aria-label="breadcrumb"><ol class="breadcrumb small"><li class="breadcrumb-item"><a href="{{ route('kelurahan.dashboard') }}">Dashboard Desa</a></li><li class="breadcrumb-item"><a href="{{ route('kelurahan.letter-types.index') }}">Master Jenis Surat</a></li><li class="breadcrumb-item"><a href="{{ route('kelurahan.letter-types.edit', $letterType) }}">{{ $letterType->code }}</a></li><li class="breadcrumb-item active">Version {{ $version->version }}</li></ol></nav>

        @if (session('status'))<div class="alert alert-success" role="status">{{ session('status') }}</div>@endif
        @if ($errors->any())<div class="alert alert-danger" role="alert"><strong>Configuration belum dapat disimpan atau dipublish.</strong><ul class="mb-0 mt-2">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        @if ($version->isPublished())<div class="alert alert-info">Version ini sudah dipublish pada {{ $version->published_at?->format('d M Y H:i') }} dan bersifat immutable. Buat draft version berikutnya untuk perubahan.</div>@elseif (! $isEditable)<div class="alert alert-warning">Akun ini memiliki akses review saja dan tidak dapat mengubah configuration.</div>@endif

        <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3 mb-4">
            <div><p class="admin-eyebrow mb-1">Configuration Version</p><h1 class="h2 fw-bold mb-1">{{ $letterType->name }} · v{{ $version->version }}</h1><p class="text-secondary mb-0"><code>{{ $letterType->code }}</code> · <span class="badge text-bg-{{ $version->isPublished() ? 'success' : 'warning' }}">{{ $version->status->value }}</span></p></div>
            <div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-secondary" href="{{ route('kelurahan.letter-types.edit', $letterType) }}">Kembali ke Master</a>@if ($version->isPublished() && auth()->user()->can('update', $letterType) && ! $letterType->versions->contains(fn ($candidate) => $candidate->isDraft()))<form method="POST" action="{{ route('kelurahan.letter-types.versions.store', $letterType) }}">@csrf<button class="btn btn-primary" type="submit">Buat Draft Baru</button></form>@endif</div>
        </div>

        <nav class="card border-0 shadow-sm mb-4" aria-label="Tahapan configuration"><div class="card-body d-flex flex-wrap gap-2"><a class="btn btn-outline-primary btn-sm" href="#information">1. Informasi Dasar</a><a class="btn btn-outline-primary btn-sm" href="#requirements">2. Persyaratan</a><a class="btn btn-outline-primary btn-sm" href="#fields">3. Field Form</a><a class="btn btn-outline-primary btn-sm" href="#workflow">4. Workflow</a><a class="btn btn-outline-primary btn-sm" href="#review">5. Review</a><a class="btn btn-outline-primary btn-sm" href="#publish">6. Publish</a></div></nav>

        <section id="information" class="card border-0 shadow-sm mb-4" aria-labelledby="information-heading"><div class="card-body p-4"><p class="admin-eyebrow mb-1">Langkah 1</p><h2 id="information-heading" class="h5 fw-bold">Informasi Dasar</h2><dl class="row mb-0"><dt class="col-sm-3">Nama</dt><dd class="col-sm-9">{{ $letterType->name }}</dd><dt class="col-sm-3">Kode</dt><dd class="col-sm-9"><code>{{ $letterType->code }}</code></dd><dt class="col-sm-3">Status type</dt><dd class="col-sm-9">{{ $letterType->is_active ? 'Aktif' : 'Nonaktif' }}</dd><dt class="col-sm-3">Deskripsi</dt><dd class="col-sm-9">{{ $letterType->description ?: '—' }}</dd><dt class="col-sm-3">Pembuat draft</dt><dd class="col-sm-9">{{ $version->creator?->name ?? 'Sistem' }}</dd></dl>@can('update', $letterType)<div class="mt-3"><a class="btn btn-outline-primary btn-sm" href="{{ route('kelurahan.letter-types.edit', $letterType) }}">Edit Informasi Dasar</a></div>@endcan</div></section>

        @include('kelurahan.letter-types.versions._requirements')
        @include('kelurahan.letter-types.versions._fields')
        @include('kelurahan.letter-types.versions._workflow')

        <section id="review" class="card border-0 shadow-sm mb-4" aria-labelledby="review-heading"><div class="card-body p-4"><p class="admin-eyebrow mb-1">Langkah 5</p><h2 id="review-heading" class="h5 fw-bold mb-3">Review Configuration</h2><div class="row g-3"><div class="col-sm-4"><div class="bg-light rounded-3 p-3"><small class="text-secondary d-block">Persyaratan</small><strong class="fs-4">{{ $version->requirements->count() }}</strong>@if ($unconfiguredRequirements > 0)<small class="text-danger d-block">{{ $unconfiguredRequirements }} evidence belum dikonfigurasi</small>@endif</div></div><div class="col-sm-4"><div class="bg-light rounded-3 p-3"><small class="text-secondary d-block">Field Form</small><strong class="fs-4">{{ $version->fieldDefinitions->count() }}</strong></div></div><div class="col-sm-4"><div class="bg-light rounded-3 p-3"><small class="text-secondary d-block">Workflow Step</small><strong class="fs-4">{{ $version->workflowSteps->count() }}</strong><small class="text-secondary d-block">Terakhir: {{ $version->workflowSteps->last()?->action?->label() ?? 'Belum ada' }}</small></div></div></div>@if ($version->configuration_snapshot)<details class="mt-4"><summary class="fw-semibold">Published configuration snapshot</summary><pre class="bg-dark text-light rounded-3 p-3 mt-3 overflow-auto"><code>{{ json_encode($version->configuration_snapshot, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) }}</code></pre></details>@endif</div></section>

        <section id="publish" class="card border-0 shadow-sm" aria-labelledby="publish-heading"><div class="card-body p-4"><p class="admin-eyebrow mb-1">Langkah 6</p><h2 id="publish-heading" class="h5 fw-bold mb-2">Publish</h2><p class="text-secondary">Publish mengunci version, persyaratan, field, workflow, dan snapshot configuration. Published version tidak digunakan oleh runtime VillageLetter pada Phase 2.</p>@if ($isEditable)<div class="d-flex flex-column flex-sm-row justify-content-between gap-3"><form method="POST" action="{{ route('kelurahan.letter-type-versions.destroy', $version) }}" onsubmit="return confirm('Hapus draft version ini beserta seluruh configuration-nya?')">@csrf @method('DELETE')<button class="btn btn-outline-danger" type="submit">Hapus Draft</button></form><form method="POST" action="{{ route('kelurahan.letter-type-versions.publish', $version) }}" onsubmit="return confirm('Publish version ini? Configuration tidak dapat diubah setelah publish.')">@csrf<button class="btn btn-success" type="submit">Validasi dan Publish</button></form></div>@else<span class="badge text-bg-{{ $version->isPublished() ? 'success' : 'secondary' }}">{{ $version->isPublished() ? 'Published dan immutable' : 'Read-only' }}</span>@endif</div></section>
    </main>
@endsection
