@extends('layouts.app')

@section('title', 'Konfigurasi Posyandu - SIGAP WARGA')

@section('content')
<main id="main-content" class="container py-5">
    <div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><span class="badge text-bg-warning mb-2">PROTOTYPE</span><h1 class="h2">Konfigurasi Posyandu</h1><p class="text-secondary">Super Admin hanya mengatur lokasi dan penugasan; isi pelayanan tidak ditampilkan di sini.</p></div><a class="btn btn-outline-secondary" href="{{ route('dashboard') }}">Kembali</a></div>
    @if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
    <div class="row g-4 mb-4">
        <div class="col-lg-6"><section class="card h-100 border-0 shadow-sm"><div class="card-body p-4"><h2 class="h4">Tambah Lokasi</h2><form method="POST" action="{{ route('admin.posyandu.sites.store') }}">@csrf<div class="mb-3"><label class="form-label" for="rt_id">Wilayah</label><select id="rt_id" name="rt_id" class="form-select" required>@foreach($rts as $rt)<option value="{{ $rt->id }}">{{ $rt->rw->code }} / {{ $rt->code }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label" for="name">Nama Posyandu</label><input id="name" name="name" class="form-control" required></div><div class="mb-3"><label class="form-label" for="address">Alamat</label><textarea id="address" name="address" class="form-control"></textarea></div><button class="btn btn-primary" type="submit">Simpan Lokasi</button></form></div></section></div>
        <div class="col-lg-6"><section class="card h-100 border-0 shadow-sm"><div class="card-body p-4"><h2 class="h4">Tugaskan Petugas</h2><form method="POST" action="{{ route('admin.posyandu.staff.store') }}">@csrf<div class="mb-3"><label class="form-label" for="posyandu_site_id">Posyandu</label><select id="posyandu_site_id" name="posyandu_site_id" class="form-select" required>@foreach($sites as $site)<option value="{{ $site->id }}">{{ $site->name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label" for="user_id">Pengguna</label><select id="user_id" name="user_id" class="form-select" required>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }} · {{ $user->role->value }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label" for="role">Peran Posyandu</label><select id="role" name="role" class="form-select" required>@foreach($staffRoles as $role)<option value="{{ $role->value }}">{{ $role->label() }}</option>@endforeach</select></div><button class="btn btn-primary" type="submit" @disabled($sites->isEmpty())>Simpan Penugasan</button></form></div></section></div>
    </div>
    <section class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h4">Lokasi dan Petugas</h2>@forelse($sites as $site)<div class="border-bottom py-3"><strong>{{ $site->name }}</strong><div class="small text-secondary">{{ $site->rt->rw->code }} / {{ $site->rt->code }}</div><div class="d-flex flex-wrap gap-2 mt-2">@forelse($site->staffAssignments as $assignment)<span class="badge text-bg-light">{{ $assignment->user->name }} · {{ $assignment->role->label() }}</span>@empty<span class="text-secondary small">Belum ada petugas.</span>@endforelse</div></div>@empty<p class="text-secondary">Belum ada lokasi Posyandu.</p>@endforelse</div></section>
</main>
@endsection
